#!/bin/sh

echo " $(top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf "%s%.1f%%\n", prefix, 100 - v }')  $(sensors | grep temp1 | head -1 | awk '{print $2}')"

# case "$1" in
#     --popup)
#         notify-send "CPU time (%)" "$(ps axch -o cmd:10,pcpu k -pcpu | head | awk '$0=$0"%"' )"
#         ;;
#     *)
#         echo " $(grep 'cpu ' /proc/stat | awk '{cpu_usage=($2+$4)*100/($2+$4+$5)}
#         END {printf "%0.2f%", cpu_usage}')  $(sensors | grep temp1 | head -1 | awk '{print $2}')"
#         ;;
# esac
